// Auto-generated by scripts/gen-barrels.js at 2025-06-22T08:42:41.791Z
export { default as TableImageCell } from "./TableImageCell";
export * from "./TableImageCell.types";
export * from "./TableImageCell.hooks";
export * from "./TableImageCell.utils";
