const fs = require("fs");
const path = require("path");

const EXCLUDE = ["__mocks__", "__tests__", "themes", "test", "stories", ".DS_Store"];
const ALLOW_FILE_EXTS = [".tsx", ".ts", ".js", ".jsx"];

const EXTRA_EXPORT_PATTERNS = [
  ".utils.ts",
  ".helper.ts",
  ".hooks.ts",
  ".service.ts"
  // thêm nếu cần, ví dụ: ".context.ts"
];

function getTimestampComment() {
  const now = new Date();
  return `// Auto-generated by scripts/gen-barrels.js at ${now.toISOString()}`;
}

function genBarrel(dir) {
  const items = fs.readdirSync(dir);
  const dirs = [];
  const files = [];

  for (const item of items) {
    const full = path.join(dir, item);
    if (EXCLUDE.includes(item)) continue;
    if (fs.statSync(full).isDirectory()) {
      dirs.push(item);
    } else if (
      ALLOW_FILE_EXTS.some((ext) => item.endsWith(ext)) &&
      !item.startsWith("index.") &&
      !item.endsWith(".test.tsx") &&
      !item.endsWith(".stories.tsx")
    ) {
      files.push(item);
    }
  }

  // Ưu tiên export default (component) trước, rồi export all types
  const exportLines = [
    // Export component default
    ...files
      .filter((f) => f.endsWith(".tsx") || f.endsWith(".js") || f.endsWith(".jsx"))
      .filter((f) => !EXTRA_EXPORT_PATTERNS.some((pat) => f.endsWith(pat)))
      .map((f) => {
        const compName = f.replace(/\.(tsx|jsx|js)$/, "");
        return `export { default as ${compName} } from "./${compName}";`;
      }),
    // Export types
    ...files
      .filter((f) => f.endsWith(".types.ts"))
      .map((f) => {
        const compName = f.replace(/\.types\.ts$/, "");
        return `export * from "./${compName}.types";`;
      }),
    // Export helpers/utils/hooks/service (không dùng default, chỉ export *)
    ...files
      .filter((f) => EXTRA_EXPORT_PATTERNS.some((pat) => f.endsWith(pat)))
      .map((f) => {
        const utilName = f.replace(/\.(utils|helper|hooks|service)\.ts$/, "");
        // Để rõ ràng, export * from từng file helper/utils
        return `export * from "./${utilName}.${f.split('.').slice(-2,-1)[0]}";`;
      }),
    // Export folder con
    ...dirs.map((d) => `export * from "./${d}";`),
  ];

  if (exportLines.length) {
    const outFile = path.join(dir, "index.ts");
    fs.writeFileSync(
      outFile,
      getTimestampComment() + "\n" +
      exportLines.join("\n") + "\n"
    );
    console.log("Generated:", outFile);
  }

  // Đệ quy cho mọi folder con
  for (const d of dirs) {
    genBarrel(path.join(dir, d));
  }
}

// Đường dẫn tới thư mục molecules
const ROOT = path.join(__dirname, "../src/components/ui/molecules");
genBarrel(ROOT);
